Traceback (most recent call last):
  File "./cc-unprop-size-test.py", line 9, in <module>
    tst_image_name = os.environ['NIMBUS_TEST_IMAGE']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'NIMBUS_TEST_IMAGE'
